services:
  bot:
    build: .
    container_name: tsn_bot
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000" # Expose FastAPI WebApp
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    command: python -m app.main

  mongo:
    image: mongo:latest
    container_name: tsn_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tsn_bot
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  redis:
    image: redis:alpine
    container_name: tsn_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
